name: Build snapshot
permissions: write-all
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Prepare build environment
        run: |
          sudo mkdir -p /etc/pacman.d
          echo "Server = https://ftp.sh.cvut.cz/arch/\$repo/os/\$arch" | sudo tee /etc/pacman.d/mirrorlist > /dev/null
          mkdir -p tools
          curl -L -o tools/hdiffpatch_v4.8.0_bin_linux64.zip https://github.com/sisong/HDiffPatch/releases/download/v4.8.0/hdiffpatch_v4.8.0_bin_linux64.zip
          unzip tools/hdiffpatch_v4.8.0_bin_linux64.zip -d tools
          sudo cp tools/linux64/* /usr/bin/
          sudo chmod +x /usr/bin/hdiffz
          rm -rf tools
          git clone --recurse-submodules https://github.com/immutarch/builder
          sudo cp builder/pacman.conf /etc/pacman.conf
          sudo pacman-key --init
      - name: Build image 
        run: |
          mkdir -p $(pwd)/output $(pwd)/workdir
          sudo bash builder/build.sh --flavor beta --snapshot_ver remote --workdir $(pwd)/workdir --output-dir $(pwd)/output
          sudo chmod 777 -R $(pwd)/output $(pwd)/index*
          sha256sum $(pwd)/output/$(cat /tmp/build_temp_ver).img.zst | awk '{print $1'} > $(pwd)/output/$(cat /tmp/build_temp_ver).img.zst.sha256
          echo "BUILDTAG=$(cat /tmp/builder-releasetag)" >> $GITHUB_ENV
          echo "BUILDIMG=$(cat /tmp/build_temp_ver)" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.BUILDTAG }}
          target_commitish: ${{ github.sha }}
          name: ${{ env.BUILDIMG }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            output/${{ env.BUILDIMG }}.img.zst
            output/${{ env.BUILDIMG }}.img.zst.sha256
            index1/incremental_patch.index1
            output/patch.incremental_conditions
            
