name: Build snapshot
permissions: write-all
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-codeql: true
          remove-haskell: true
          remove-docker-images: true
      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt-get install btrfs-progs pacman-package-manager zstd git jq unzip arch-install-scripts
          sudo mkdir -p /etc/pacman.d
          echo "Server = https://ftp.sh.cvut.cz/arch/\$repo/os/\$arch" | sudo tee /etc/pacman.d/mirrorlist > /dev/null
          sudo mkdir -p tools
          curl -L -o tools/hdiffpatch_v4.8.0_bin_linux64.zip https://github.com/sisong/HDiffPatch/releases/download/v4.8.0/hdiffpatch_v4.8.0_bin_linux64.zip
          unzip tools/hdiffpatch_v4.8.0_bin_linux64.zip -d tools
          sudo cp tools/linux64/* /usr/bin/
          sudo chmod +x /usr/bin/hdiffz
          rm -rf tools
          git clone --recurse-submodules https://github.com/immutarch/builder
      - name: Build image 
        run: |
          mkdir -p $(pwd)/output $(pwd)/workdir
          sudo bash builder/build.sh --flavor beta --snapshot_ver remote --workdir $(pwd)/workdir --output-dir $(pwd)/output
          sha256sum $(pwd)/output/$(cat /tmp/build_temp_ver).img.zst | awk '{print $1'} > $(pwd)/output/$(cat /tmp/build_temp_ver).img.zst.sha256
          echo "BUILDTAG=$(cat /tmp/builder-releasetag)" >> $GITHUB_ENV
          echo "BUILDIMG=$(cat /tmp/build_temp_ver)" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.BUILDTAG }}
          target_commitish: ${{ github.sha }}
          name: ${{ env.BUILDIMG }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            output/${{ env.BUILDIMG }}.img.zst
            output/${{ env.BUILDIMG }}.img.zst.sha256
            index1/incremental_patch.index1
            index2/incremental_patch.index2
            output/patch.incremental_conditions
            
